[build]
  publish = "frontend/build"
  command = "npm install --prefix netlify/functions && cd frontend && npm install && npm run build"
  functions = "netlify/functions"

[build.environment]
  YOUTUBE_API_KEY = "AIzaSyABb8KAFgjIIfeyGI9LPn4rqWmTvrZJNeo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200