services:
  # Backend Service
  - type: web
    name: youtube-playlist-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false

  # Frontend Service  
  - type: web
    name: youtube-playlist-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false
